id: A44619A96
title: 'The Jewel Rosary: A Concise Aspiration Towards the Buddhafield of the Blessed
  Akṣobhya'
type: translation
pechas:
- IB86A686C
- I9744AF7F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:07:34.740086
  last_modified_at: 2023-01-04 12:07:34.740098
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IB86A686C/1ED1: A5E1
  I9744AF7F/7AF2: A5E1
